version: '3.1'
services:
  db:
    image: postgres
    env_file: .env
    container_name: ${PROJ_NAME}_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - web-db:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ${PROJ_NAME}_backend
    command: bash -c "sleep 5 && sh /usr/src/app/backend/init_local.sh"
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
      
volumes:
  web-db:
 


